# Generated by Django 5.2.5 on 2025-08-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('health_status', models.TextField()),
                ('children_count', models.PositiveIntegerField()),
                ('financial_status', models.CharField(max_length=30)),
                ('special_needs', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10)),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('آخر', 'آخر')], max_length=20)),
                ('resume', models.FileField(upload_to='volunteer_resumes/')),
                ('agreed_terms', models.BooleanField(default=False)),
                ('commitment_statement', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('Visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('oxygen_level', models.PositiveIntegerField()),
                ('blood_sugar', models.PositiveIntegerField()),
                ('general_health_status', models.CharField(choices=[('جيد', 'جيد'), ('متوسط', 'متوسط'), ('يحتاج متابعة', 'يحتاج متابعة'), ('حرج', 'حرج')], max_length=20)),
                ('health_notes', models.TextField(blank=True)),
                ('medical_need', models.CharField(choices=[('فحص دوري', 'فحص دوري'), ('دواء', 'دواء'), ('مرافقة لطبيب', 'مرافقة لطبيب')], max_length=30)),
                ('psych_status', models.CharField(choices=[('مستقر', 'مستقر'), ('مكتئب', 'مكتئب'), ('وحيد', 'وحيد'), ('متحسن', 'متحسن')], max_length=20)),
                ('social_status', models.CharField(choices=[('يتواصل مع الجيران', 'يتواصل مع الجيران'), ('لديه زيارات متقطعة', 'لديه زيارات متقطعة'), ('لا يوجد دعم عائلي', 'لا يوجد دعم عائلي')], max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('living_need', models.CharField(choices=[('غذاء', 'غذاء'), ('أدوات منزلية', 'أدوات منزلية'), ('أدوية', 'أدوية')], max_length=30)),
                ('support_need', models.CharField(choices=[('زيارة إضافية', 'زيارة إضافية'), ('جلسة استماع', 'جلسة استماع'), ('نشاط جماعي', 'نشاط جماعي')], max_length=30)),
                ('general_status_percent', models.PositiveIntegerField(default=0)),
                ('elder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.elder')),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='pdf_Analysis/')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('volunteer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.volunteer')),
            ],
        ),
    ]
