# Generated by Django 5.2.5 on 2025-09-02 12:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('health_status', models.CharField(blank=True, max_length=10, null=True)),
                ('children_count', models.PositiveIntegerField()),
                ('financial_status', models.CharField(max_length=30)),
                ('special_needs', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=10)),
                ('marital_status', models.CharField(choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('آخر', 'آخر')], max_length=20)),
                ('resume', models.FileField(upload_to='volunteer_resumes/')),
                ('agreed_terms', models.BooleanField(default=False)),
                ('commitment_statement', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('oxygen_level', models.PositiveIntegerField()),
                ('blood_sugar', models.PositiveIntegerField()),
                ('general_health_status', models.CharField(choices=[('جيد', 'جيد'), ('متوسط', 'متوسط'), ('يحتاج متابعة', 'يحتاج متابعة'), ('حرج', 'حرج')], max_length=20)),
                ('health_notes', models.TextField(blank=True)),
                ('medical_need', models.CharField(choices=[('فحص دوري', 'فحص دوري'), ('دواء', 'دواء'), ('مرافقة لطبيب', 'مرافقة لطبيب')], max_length=30)),
                ('psych_status', models.CharField(choices=[('مستقر', 'مستقر'), ('مكتئب', 'مكتئب'), ('وحيد', 'وحيد'), ('متحسن', 'متحسن')], max_length=20)),
                ('social_status', models.CharField(choices=[('يتواصل مع الجيران', 'يتواصل مع الجيران'), ('لديه زيارات متقطعة', 'لديه زيارات متقطعة'), ('لا يوجد دعم عائلي', 'لا يوجد دعم عائلي')], max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('living_need', models.CharField(choices=[('غذاء', 'غذاء'), ('أدوات منزلية', 'أدوات منزلية'), ('أدوية', 'أدوية')], max_length=30)),
                ('support_need', models.CharField(choices=[('زيارة إضافية', 'زيارة إضافية'), ('جلسة استماع', 'جلسة استماع'), ('نشاط جماعي', 'نشاط جماعي')], max_length=30)),
                ('general_status_percent', models.PositiveIntegerField(default=0)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.elder')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='pdf_analysis/')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareBridge.volunteer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('volunteer', 'Volunteer')], default='volunteer', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
