# Generated by Django 5.2.5 on 2025-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='visit_id',
            new_name='visit',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='visit_id',
            new_name='visit',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='volunteer_id',
            new_name='volunteer',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='elder_id',
            new_name='elder',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='Visit_id',
            new_name='visit_id',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='volunteer_id',
            new_name='volunteer',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='pdf_file',
            field=models.FileField(upload_to='pdf_analysis/'),
        ),
    ]
