# Generated by Django 5.2.5 on 2025-09-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0002_alter_volunteer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_login',
        ),
    ]
