# Generated by Django 5.2.5 on 2025-09-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0003_remove_volunteer_email_remove_volunteer_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='is_admin',
        ),
    ]
