# Generated by Django 5.2.5 on 2025-09-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0003_remove_volunteer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='resume',
            field=models.FileField(default=True, upload_to='volunteer_resumes/'),
        ),
    ]
