# Generated by Django 5.2.5 on 2025-09-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0004_alter_volunteer_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='resume',
            field=models.FileField(upload_to='volunteer_resumes/'),
        ),
    ]
