# Generated by Django 5.2.5 on 2025-09-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0006_alter_elder_image_alter_volunteer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(default='لديك زيارة جديدة !'),
        ),
    ]
