# Generated by Django 5.2.5 on 2025-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0007_notification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='is_submitted',
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('missing', 'missing'), ('pending', 'pending'), ('done', 'done')], default='missing', max_length=20),
        ),
    ]
