# Generated by Django 5.2.5 on 2025-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0008_remove_visit_is_submitted_alter_visit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='visit',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='blood_sugar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='general_health_status',
            field=models.CharField(blank=True, choices=[('جيد', 'جيد'), ('متوسط', 'متوسط'), ('يحتاج متابعة', 'يحتاج متابعة'), ('حرج', 'حرج')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='health_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='living_need',
            field=models.CharField(blank=True, choices=[('غذاء', 'غذاء'), ('أدوات منزلية', 'أدوات منزلية'), ('أدوية', 'أدوية')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='medical_need',
            field=models.CharField(blank=True, choices=[('فحص دوري', 'فحص دوري'), ('دواء', 'دواء'), ('مرافقة لطبيب', 'مرافقة لطبيب')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='oxygen_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='psych_status',
            field=models.CharField(blank=True, choices=[('مستقر', 'مستقر'), ('مكتئب', 'مكتئب'), ('وحيد', 'وحيد'), ('متحسن', 'متحسن')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='social_status',
            field=models.CharField(blank=True, choices=[('يتواصل مع الجيران', 'يتواصل مع الجيران'), ('لديه زيارات متقطعة', 'لديه زيارات متقطعة'), ('لا يوجد دعم عائلي', 'لا يوجد دعم عائلي')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='support_need',
            field=models.CharField(blank=True, choices=[('زيارة إضافية', 'زيارة إضافية'), ('جلسة استماع', 'جلسة استماع'), ('نشاط جماعي', 'نشاط جماعي')], max_length=30, null=True),
        ),
    ]
