# Generated by Django 5.2.5 on 2025-09-05 13:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0009_remove_visit_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='CareBridge.visit'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='CareBridge.visit'),
        ),
    ]
