# Generated by Django 5.2.5 on 2025-09-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0010_alter_analysis_pdf_file_alter_analysis_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elder',
            name='children_count',
        ),
        migrations.RemoveField(
            model_name='elder',
            name='financial_status',
        ),
        migrations.RemoveField(
            model_name='elder',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='elder',
            name='special_needs',
        ),
        migrations.AddField(
            model_name='elder',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
    ]
