# Generated by Django 5.2.5 on 2025-09-22 02:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareBridge', '0012_volunteer_is_verified_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='elder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
